### ISSUE TITLE
Having a tough time getting one-click-hugo-cms running locally.

### ISSUE THREAD

**Issue by jaegz** [netlify-templates/one-click-hugo-cms#10]
## Having a tough time getting one-click-hugo-cms running locally. 
(Maybe these issues stem from victor/hugo itself rather than this project?)

**System** 
Win7 64bit
node -v 8.9.1
npm -v 5.0.3

### Installing in both cmd and bash

```
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none was installed.
npm WARN react-toolbox@2.0.0-beta.12 requires a peer of react-transition-group@^1.1.3 but none was installed.
npm WARN slate-edit-list@0.8.0 requires a peer of slate@^0.23.0 but none was installed.
npm WARN slate-plain-serializer@0.1.14 requires a peer of slate@^0.26.1 but none was installed.
npm WARN slate-base64-serializer@0.1.22 requires a peer of slate@^0.28.2 but none was installed.
npm WARN slate-prop-types@0.1.13 requires a peer of slate@^0.26.1 but none was installed.
npm WARN victor-hugo@1.0.0 No repository field.

npm ERR! Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
```

### Ignoring the warnings and running `npm start`

```
[11:46:51] Failed to load external module babel-register
[11:46:51] Failed to load external module babel-core/register
[11:46:51] Failed to load external module babel/register
[11:46:51] Local gulp not found in ~\test_netlifycms\one-click-hugo-cms
[11:46:51] Try running: npm install gulp
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jaegz\AppData\Roaming\npm-cache\_logs\2017-11-15T16_46_51_947Z-debug.log
```

### Deleting the `node_modules` folder, updating `package.json` packages to the latest versions, and running `npm install` again
```
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN victor-hugo@1.0.0 No repository field.
```
### Ignoring the warnings and running `npm start` again
```
[11:50:47] Failed to load external module babel-register
[11:50:47] Failed to load external module babel-core/register
[11:50:47] Failed to load external module babel/register
[11:50:47] Local gulp not found in ~\test_netlifycms\one-click-hugo-cms
[11:50:47] Try running: npm install gulp
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jaegz\AppData\Roaming\npm-cache\_logs\2017-11-15T16_50_47_083Z-debug.log
```

### Debug log (2017-11-15T16_50_47_083Z-debug.log)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jaegz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle victor-hugo@1.0.0~prestart: victor-hugo@1.0.0
6 silly lifecycle victor-hugo@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle victor-hugo@1.0.0~start: victor-hugo@1.0.0
8 verbose lifecycle victor-hugo@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle victor-hugo@1.0.0~start: PATH: C:\Users\jaegz\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\jaegz\test_netlifycms\one-click-hugo-cms\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jaegz\bin;C:\Users\jaegz\Downloads\cmder\bin;C:\Users\jaegz\Downloads\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\jaegz\Downloads\cmder\vendor\conemu-maximus5;C:\Users\jaegz\Downloads\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\Windows\System32;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Ruby193\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files\Amazon\AWSCLI;C:\Go\bin;C:\Users\jaegz\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\php;C:\curl;C:\Program Files\nodejs;C:\Program Files (x86)\Yarn\bin;C:\Windows\System32;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Python34;C:\Python34\Scripts;C:\Users\jaegz\AppData\Roaming\Python\Scripts;C:\Hugo\bin;C:\Users\jaegz\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\Users\jaegz\AppData\Roaming\npm;C:\Users\jaegz\bash-scripts;C:\Users\jaegz\AppData\Local\Yarn\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\Users\jaegz\Downloads\cmder
10 verbose lifecycle victor-hugo@1.0.0~start: CWD: C:\Users\jaegz\test_netlifycms\one-click-hugo-cms
11 silly lifecycle victor-hugo@1.0.0~start: Args: [ '/d /s /c', 'gulp server' ]
12 silly lifecycle victor-hugo@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle victor-hugo@1.0.0~start: Failed to exec start script
14 verbose stack Error: victor-hugo@1.0.0 start: `gulp server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\jaegz\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\jaegz\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid victor-hugo@1.0.0
16 verbose cwd C:\Users\jaegz\test_netlifycms\one-click-hugo-cms
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jaegz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.9.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error victor-hugo@1.0.0 start: `gulp server`
23 error Exit status 1
24 error Failed at the victor-hugo@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
### `npm install gulp --save` & `npm start`
```
> victor-hugo@1.0.0 start C:\Users\jaegz\test_netlifycms\one-click-hugo-cms
> gulp server

[12:21:19] Failed to load external module babel-register
[12:21:19] Failed to load external module babel-core/register
[12:21:19] Failed to load external module babel/register
C:\Users\jaegz\test_netlifycms\one-click-hugo-cms\gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from "gulp";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\jaegz\test_netlifycms\one-click-hugo-cms\node_modules\gulp\bin\gulp.js:116:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jaegz\AppData\Roaming\npm-cache\_logs\2017-11-15T17_21_19_166Z-debug.log
```
### Looks like babel and the config files are out of sync since import throws a syntax error?

**Comment by erquhart** [comment]
@jaegz there have been a few updates since you posted this, can you confirm whether its still an issue?

**Comment by jaegz** [comment]
@erquhart thanks I'll give this another go and get back to you

**Comment by vorcigernix** [comment]
Similar on OSX with node 10. Using node v10.5.0 (npm v6.1.0). Yarn does not work at all, npm show a several warnings and security vulnerabilities, but somehow works. Is there any branch I should switch to?

**Comment by erquhart** [comment]
Just updated and ran locally with yarn and didn't encounter any problems. Using Node 10.13.0, npm 6.4.1 and yarn 1.12.1.

**Comment by erquhart** [comment]
Really want to help, but need a way to reliably reproduce, seems to be an environment issue so far.

**Comment by coryalini** [comment]
Running into the same issues with yarn 1.13.0, npm 6.8.0 and node 11.8.0 on osx. Has anyone found any solutions?

**Comment by numbfall** [comment]
The error you got after doing `npm install gulp` is due to gulp dependency upgrading gulp to `gulp 4.0.0`. 

_one-click-hugo-cms_ will not work with gulp 4. More specifically the `gulpfile.babel.js` is not written to work on gulp 4.

Try and revert gulp to version 3 `"gulp": "^3.9.1",` in `package.json`. See if the problem persists. Refresh the node_modules folder if possible

**Comment by GuzhengAlive** [comment]
I have also been seeing this issue but environment/system dependent. I did get it running on a windows 10 machine by uninstalling and then reinstalling node and npm. I wish I followed the steps I took but did not. Meanwhile my OSX system continues to error out. Using gulp 3.9.1 got farther in the process but hit the error:
```
[18:53:41] 'js' errored after 44 ms
[18:53:41] WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. 
```
And then various others. Just offering my experience.
